if (process.env.NODE_ENV !== "production") {
  require("dotenv").config();
}

const express = require("express");
const cors = require("cors");
const Groq = require("groq-sdk");
const { GoogleGenerativeAI } = require("@google/generative-ai");
const Tesseract = require("tesseract.js");
const { S3Client, PutObjectCommand } = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");

// ── Config ──────────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 3000;
const GROQ_API_KEY = process.env.GROQ_API_KEY;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

if (!GROQ_API_KEY) {
  console.error("[ERROR] GROQ_API_KEY is missing. Add it to your .env file.");
  process.exit(1);
}

// ── Groq client ──────────────────────────────────────────────────────────────
const groq = new Groq({ apiKey: GROQ_API_KEY });

// ── Gemini client (optional – used for image analysis) ───────────────────────
let geminiModel = null;
if (GEMINI_API_KEY) {
  try {
    const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
    geminiModel = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    console.log("[SERVER] Gemini client initialised (image analysis enabled).");
  } catch (e) {
    console.warn("[SERVER] Gemini init failed – image analysis will be skipped.", e.message);
  }
} else {
  console.warn("[SERVER] GEMINI_API_KEY not set – image analysis disabled.");
}

// ── AWS S3 Client (optional – used for evidence evidence_url hook) ───────────
let s3Client = null;
const S3_BUCKET_NAME = process.env.S3_BUCKET_NAME;

if (process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY && process.env.AWS_REGION && S3_BUCKET_NAME) {
  try {
    s3Client = new S3Client({
      region: process.env.AWS_REGION,
      credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      },
    });
    console.log("[SERVER] AWS S3 client initialised (media storage enabled).");
  } catch (e) {
    console.warn("[SERVER] S3 init failed – upload will be skipped.", e.message);
  }
} else {
  console.warn("[SERVER] AWS credentials or bucket not set – S3 uploads disabled.");
}

// ── Express app ──────────────────────────────────────────────────────────────
const app = express();

// Allow all origins explicitly (required for deployed frontends)
app.use(cors({
  origin: "*",
  methods: ["GET", "POST", "OPTIONS"],
  allowedHeaders: ["Content-Type", "Authorization"],
}));
app.options("*", cors()); // handle preflight for all routes

// Raise JSON body limit to 10 MB to accommodate base64-encoded images
app.use(express.json({ limit: "10mb" }));
app.use(express.urlencoded({ limit: "10mb", extended: true }));

// ── System prompt ────────────────────────────────────────────────────────────
const SYSTEM_PROMPT = `You are a legal document assistant for Indian Police. Generate a formal First Information Report (FIR) in the official Indian police format.

OUTPUT RULES:
- Do NOT return JSON. Generate FIR as plain formatted text with headings and bullet points.
- Output exactly TWO blocks separated by the line: ===HINDI===
- First block = English FIR. Second block = Hindi FIR.
- Do NOT add any text before the English FIR or after the Hindi FIR.
- Do NOT use markdown, code fences, or HTML.
- Do NOT fabricate IPC/BNS sections. Include only clearly applicable sections.

CLOSING FORMAT RULES (STRICTLY ENFORCED):
- The FIR MUST end with the NOTE section. No text must appear after NOTE.
- Do NOT include any of the following:
    • "Electronically Generated Document" or any similar line
    • "Document Timestamp" or any system-generated timestamp line
    • Website links, URLs, or metadata of any kind
    • Any footer indicating this was generated by software or an AI system
- Use an official, formal tone for all closing sections.

FIR STRUCTURE (apply to BOTH English and Hindi):
- Each section heading on its own line in ALL CAPS followed by a colon.
- Every piece of content under a heading starts with "  • " (two spaces, bullet, space).
- Leave exactly one blank line between sections.
- Use this exact order of sections with NO additions, duplications, or omissions:

  1. CASE DIARY NUMBER
  2. DATE AND TIME OF OCCURRENCE
  3. PLACE OF OCCURRENCE
  4. INFORMATION PROVIDED BY
  5. STATEMENT
  6. DETAILS OF INJURED / DECEASED PERSON
  7. NATURE OF INJURIES
  8. POLICE STATION
  9. NAME AND ADDRESS OF COMPLAINANT / VICTIM
  10. SECTIONS APPLIED
  11. SIGNATURE OF INFORMANT
  12. SIGNATURE OF OFFICER-IN-CHARGE
  13. DATE OF REPORT
  14. NOTE

EXAMPLE OUTPUT FORMAT (English):
CASE DIARY NUMBER:
  • CD No. 142/2024

DATE AND TIME OF OCCURRENCE:
  • Date: 15/04/2024
  • Time: 10:30 PM

PLACE OF OCCURRENCE:
  • Near Connaught Place, New Delhi, Delhi - 110001

INFORMATION PROVIDED BY:
  • Rahul Sharma (Eyewitness)

STATEMENT:
  • On the night of 15th April 2024, at approximately 10:30 PM, a speeding vehicle struck a pedestrian at Connaught Place. The victim sustained serious injuries and was immediately rushed to hospital. The accused fled the scene.

DETAILS OF INJURED / DECEASED PERSON:
  • Name: Not identified
  • Age: Approximately 35 years
  • Gender: Male

NATURE OF INJURIES:
  • Serious head injuries and multiple fractures reported. Victim in critical condition.

POLICE STATION:
  • Connaught Place Police Station, New Delhi

NAME AND ADDRESS OF COMPLAINANT / VICTIM:
  • Name: Rahul Sharma
  • Address: 12, Rajpur Road, Delhi - 110054

SECTIONS APPLIED:
  • BNS Section 281 (Rash driving on public way)
  • BNS Section 125 (Act endangering life)

SIGNATURE OF INFORMANT:
  • (Signed)
  • Rahul Sharma

SIGNATURE OF OFFICER-IN-CHARGE:
  • (Signed)
  • Inspector Anil Kumar
  • Connaught Place Police Station

DATE OF REPORT:
  • 15/04/2024

NOTE:
  • This report has been recorded based on the information provided by the informant and is subject to further investigation.

HINDI RULES (for fir_hindi):
- Translate ALL content — including section headings — into formal legal Hindi.
- Do NOT use English words. Use proper Hindi equivalents:
  - accident → दुर्घटना, vehicle → वाहन, nearby → निकट, injuries → चोटें, complainant → शिकायतकर्ता, station → थाना
- Hindi section headings (use exactly):
  केस डायरी संख्या: | घटना की तिथि एवं समय: | घटनास्थल: | सूचना प्रदाता: | विवरण: | घायल / मृतक का विवरण: | चोटों की प्रकृति: | थाना: | शिकायतकर्ता / पीड़ित का नाम एवं पता: | लागू धाराएं: | सूचनादाता के हस्ताक्षर: | थानाध्यक्ष / प्रभारी अधिकारी के हस्ताक्षर: | रिपोर्ट की तिथि: | नोट:
- Bullet format remains: "  • " prefix`;

// ── GET /test ────────────────────────────────────────────────────────────────
app.get("/test", (req, res) => {
  console.log("[GET /test] Health check requested.");
  return res.json({ message: "API working" });
});

// ── GET / ────────────────────────────────────────────────────────────────────
app.get("/", (req, res) => {
  return res.json({ status: "ok", endpoints: ["POST /generate-fir", "POST /trigger-sos", "GET /test"] });
});

// ── POST /trigger-sos ────────────────────────────────────────────────────────
app.post("/trigger-sos", (req, res) => {
  const { latitude, longitude, timestamp } = req.body || {};

  console.log("\n🚨🚨🚨 [EMERGENCY SOS TRIGGERED] 🚨🚨🚨");
  console.log(`📍 Location : ${latitude}, ${longitude}`);
  console.log(`⏰ Time     : ${timestamp || new Date().toISOString()}`);

  return res.json({
    success: true,
    message: "Emergency services and local authorities have been notified."
  });
});
//---------------------------------------------------
// cleanFIRText: strip leftover placeholder brackets, preserve line breaks
function cleanFIRText(text) {
  if (typeof text !== "string") return String(text);
  return text
    .replace(/\[.*?\]/g, "") // remove placeholders like [To be filled]
    .trim();
}

//---------------------------------------------------
// stripAfterNote: hard-truncate anything that appears after the NOTE section.
// Works for both English (NOTE:) and Hindi (नोट:) blocks.
function stripAfterNote(text) {
  if (typeof text !== "string") return String(text);

  // Match the NOTE heading in English or Hindi
  const noteMatch = text.match(/(?:^|\n)(NOTE\s*:|\u0928\u094b\u091f\s*:)/i);
  if (!noteMatch || noteMatch.index === undefined) return text.trim();

  // Position of the NOTE heading
  const noteStart = noteMatch.index;
  const beforeNote = text.substring(0, noteStart);
  const fromNote   = text.substring(noteStart);

  // Walk line by line: keep the heading + its bullet lines, stop at the first
  // non-bullet, non-empty line that appears AFTER at least one bullet.
  const lines    = fromNote.split(/\r?\n/);
  const kept     = [];
  let bulletSeen = false;

  for (const line of lines) {
    const isBullet = /^\s*\u2022/.test(line);   // starts with •
    const isEmpty  = line.trim() === "";

    if (kept.length === 0) {
      // Always keep the NOTE: heading line
      kept.push(line);
      continue;
    }

    if (isBullet) {
      bulletSeen = true;
      kept.push(line);
      continue;
    }

    if (bulletSeen) {
      // First non-bullet line after NOTE bullets → stop
      break;
    }

    // Empty or header lines before any bullet (shouldn't normally appear, keep anyway)
    if (isEmpty) {
      kept.push(line);
    }
  }

  return (beforeNote + kept.join("\n")).trim();
}
// ── POST /generate-fir ───────────────────────────────────────────────────────
//
// Sample curl command to test this endpoint:
//
// curl -X POST http://localhost:3000/generate-fir \
//   -H "Content-Type: application/json" \
//   -d '{"description": "A car hit a pedestrian near Connaught Place, New Delhi at night."}'
//
app.post("/generate-fir", async (req, res) => {
  try {
    const { description, image, mode } = req.body;

    // ── Input validation ─────────────────────────────────────────────────────
    if (!description || typeof description !== "string" || !description.trim()) {
      return res
        .status(400)
        .json({ error: "A non-empty 'description' string is required." });
    }

    console.log("[POST /generate-fir] Request received. Mode:", mode);
    console.log("[POST /generate-fir] Input description:", description.trim());
    console.log("[POST /generate-fir] Image provided:", !!image);
    console.log("USING MODEL: llama-3.1-8b-instant");

    // ── System Prompt Selection ──────────────────────────────────────────────
    const APPLICATION_PROMPT = `You are a legal assistant. Generate a formal police complaint/application letter based on the incident.

STRICT FORMAT:

To,
The Station House Officer,
<Police Station Name>, <City>, <State>

Subject: <Specific concise subject regarding the incident>

Respected Sir/Madam,

I would like to inform you that on <date> at approximately <time>, an incident occurred at <location>.

<Clear incident description in 2–3 paragraphs, simple and natural tone. Keep text concise (max 200–250 words)>

I request you to kindly take necessary legal action regarding this matter.

Thanking you,

Yours faithfully,

(Signature)
<Name of Applicant>
<Address of Applicant>
<Contact Number>

RULES:
* Do NOT include: blank lines like ________, placeholders like "Name of applicant:", system text, metadata, or excessive formal/robotic phrases.
* Ensure: natural human tone, proper paragraph spacing, no repetition, clean formatting.
* If name/address/date/time missing: generate realistic placeholders exactly like: "Name not provided", "Address not available", "Date not specified".

OUTPUT RULES:
- Output exactly TWO blocks separated by the line: ===HINDI===
- First block = English Application. Second block = Hindi Application.
- HINDI RULES: Translate ALL content into formal legal Hindi.
- Return ONLY clean plain text (no JSON, no markdown).`;

    const selectedPrompt = mode === "application" ? APPLICATION_PROMPT : SYSTEM_PROMPT;

    let finalDescription = description ? description.trim() : "";
    let s3Url = null;

    // ── S3 Image Extraction / Upload (Optional) ──────────────────────────────
    if (image && s3Client && S3_BUCKET_NAME) {
      try {
        console.log("[POST /generate-fir] Uploading image/frame to S3...");
        const base64Data = image.includes(",") ? image.split(",")[1] : image;
        const buffer = Buffer.from(base64Data, "base64");
        const filename = `evidence_${Date.now()}_${Math.random().toString(36).substring(2, 9)}.jpg`;

        const command = new PutObjectCommand({
          Bucket: S3_BUCKET_NAME,
          Key: filename,
          Body: buffer,
          ContentType: "image/jpeg",
          ACL: "public-read"
        });

        await s3Client.send(command);
        s3Url = `https://${S3_BUCKET_NAME}.s3.${process.env.AWS_REGION}.amazonaws.com/${filename}`;
        console.log("[POST /generate-fir] S3 Upload successful:", s3Url);
      } catch (err) {
        console.error("[POST /generate-fir] S3 upload failed:", err.message);
      }
    }

    if (image && geminiModel) {
      try {
        console.log("[POST /generate-fir] Calling Gemini for image analysis...");

        // Strip data-URL prefix if present (e.g. "data:image/jpeg;base64,")
        const base64Data = image.includes(",") ? image.split(",")[1] : image;

        const geminiResponse = await geminiModel.generateContent([
          { text: "Describe this accident or crime scene in detail for an Indian police FIR. Focus on visible injuries, vehicles, objects, and environmental context." },
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: base64Data,
            },
          },
        ]);

        const imageText = geminiResponse.response.text();
        finalDescription += "\n\nImage Analysis:\n" + imageText;
        console.log("[POST /generate-fir] Gemini image analysis appended.");
      } catch (geminiErr) {
        // Non-fatal – Groq will still run with the original description
        console.error("[POST /generate-fir] Gemini failed, falling back to text-only:", geminiErr.message);
      }
    } else if (image && !geminiModel) {
      console.warn("[POST /generate-fir] Image received but Gemini is not configured – skipping image analysis.");
    }

    // ── Tesseract OCR: vehicle number detection (optional) ───────────────────
    if (image) {
      try {
        const base64Data = image.replace(/^data:image\/\w+;base64,/, "");
        const buffer = Buffer.from(base64Data, "base64");

        const result = await Tesseract.recognize(buffer, "eng");
        const ocrText = result.data.text;

        // Match Indian vehicle number format: e.g. MH12AB1234
        const match = ocrText.match(/[A-Z]{2}[0-9]{2}[A-Z]{2}[0-9]{4}/);
        if (match) {
          finalDescription += "\n\nVehicle Number: " + match[0];
          console.log("[POST /generate-fir] OCR vehicle number found:", match[0]);
        } else {
          console.log("[POST /generate-fir] OCR ran but no vehicle number matched.");
        }
      } catch (ocrErr) {
        // Non-fatal – Groq still runs
        console.error("[POST /generate-fir] OCR failed:", ocrErr.message);
      }
    }

    // Final merge of S3 to description
    if (s3Url) {
      finalDescription += "\n\nEvidence Link: " + s3Url;
    }

    // ── Call Groq ────────────────────────────────────────────────────────────
    console.log("Final description:", finalDescription);
    const userPrompt = `Incident description:\n"${finalDescription}"`;

    const completion = await groq.chat.completions.create({
      model: "llama-3.1-8b-instant",
      messages: [
        { role: "system", content: selectedPrompt },
        { role: "user", content: userPrompt },
      ],
    });

    const raw = completion.choices[0].message.content;

    // Strip markdown code fences if model adds them
    const cleaned = raw
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    console.log("[POST /generate-fir] Cleaned LLM response:", cleaned);

    // ── Split English / Hindi ─────────────────────────────────────────────────
    // Strategy 1: explicit delimiter ===HINDI===
    // Strategy 2: Hindi section starts with "केस डायरी संख्या"
    const DELIMITER   = "===HINDI===";
    const HINDI_HEADING = "केस डायरी संख्या";

    let englishPart = cleaned;
    let hindiPart   = "";

    const explicitIndex = cleaned.indexOf(DELIMITER);
    if (explicitIndex !== -1) {
      englishPart = cleaned.substring(0, explicitIndex).trim();
      hindiPart   = cleaned.substring(explicitIndex + DELIMITER.length).trim();
      console.log("[POST /generate-fir] Split on explicit ===HINDI=== delimiter.");
    } else {
      // Fallback: detect Hindi block by its first heading
      const hindiIndex = cleaned.indexOf(HINDI_HEADING);
      if (hindiIndex !== -1) {
        englishPart = cleaned.substring(0, hindiIndex).trim();
        hindiPart   = cleaned.substring(hindiIndex).trim();
        console.log("[POST /generate-fir] Split on Hindi heading fallback.");
      } else {
        console.warn("[POST /generate-fir] No split point found; returning full text for English, empty for Hindi.");
      }
    }

    console.log("[POST /generate-fir] FIR generated successfully.");
    return res.json({
      fir_english: cleanFIRText(stripAfterNote(englishPart)),
      fir_hindi:   cleanFIRText(stripAfterNote(hindiPart)) || "Hindi version not available",
      evidence_url: s3Url
    });
  } catch (err) {
    console.error("[POST /generate-fir] Unexpected error:", err.message);
    return res
      .status(500)
      .json({ error: "Internal server error. Please try again later." });
  }
});

// ── Start ────────────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`[SERVER] FIR Generator API running on http://localhost:${PORT}`);
  console.log(`[SERVER] Test route: GET  http://localhost:${PORT}/test`);
  console.log(`[SERVER] FIR route:  POST http://localhost:${PORT}/generate-fir`);
});
